services:
    db:
      image: "postgres"
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}

    backend:
      depends_on:
        - db
      build: .
      environment:
        DB_URL:      ${DB_URL}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
      ports:
        - "8080:8080"
